config/routes.rb
Rails.application.routes.draw do
  root to: 'leaderboard#leaderboard'
  get "/leaderboard" => "leaderboard#leaderboard"
  get "/this_year" => "leaderboard#this_year"
  get "/last_year" => "leaderboard#last_year"
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  resources :users
  resources :scores, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user

  scope :this_year, -> { where("created_at >?", Date.today.beginning_of_year) }
  scope :last_year, -> { where(created_at: (Date.today.beginning_of_year - 1.year)..Date.today.beginning_of_year) }
  scope :ordered, -> { order(:date, stableford: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :invitable, invite_key: { email: Devise.email_regexp, nickname: /[a-zA-Z0-9]+/ }
  has_many :scores

  def total_score
    this_years_scores.inject(0,:+)
  end

  def total_rounds
    scores.count
  end

  def total_rounds_this_year
    scores.this_year.count
  end

  def last_years_total_score
    last_years_scores.inject(:+)
  end

  def last_years_scores
    scores.last_year.order(stableford: :desc).limit(3).pluck(:stableford)
  end

  def this_years_scores
    scores.this_year.order(stableford: :desc).limit(3).pluck(:stableford)
  end

  def best_score
    this_years_scores.first
  end

  def second_score
    this_years_scores.second
  end

  def third_score
    this_years_scores.third
  end

  def last_years_best_score
    last_years_scores.first
  end

  def last_years_second_score
    last_years_scores.second
  end

  def last_years_third_score
    last_years_scores.third
  end

  has_attached_file :avatar, styles: {
    medium: "300x300>",
    thumb: "100x100#"
  }, default_url: "https://s3-us-west-2.amazonaws.com/goats-golf/goat.jpg"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:name, :nickname, :avatar]
    devise_parameter_sanitizer.permit :account_update, keys: [:name, :nickname, :avatar]
    devise_parameter_sanitizer.permit :accept_invitation, keys: [:email, :nickname, :avatar]
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def leaderboard
    @users = User.all.sort_by{ |user| user.total_score }.reverse
  end

  def this_year
    @users = User.all.sort_by{ |user| user.total_score }.reverse
  end

  def last_year
    @users = User.all.sort_by{ |user| user.last_years_total_score }.reverse
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :authenticate_user!

  def index
    @scores = Score.all.ordered
  end

  def show
  end

  def new
    @score = Score.new
  end

  def create
    Score.create(score_params)
    redirect_to "/scores"
  end

  def score_params
    params.require(:score)
          .permit(:course, :handicap, :strokes, :stableford, :user_id, :open_round)
          .merge(date: input_date)
  end

  def input_date
    Date.civil(params[:date]["date(1i)"].to_i,
               params[:date]["date(2i)"].to_i,
               params[:date]["date(3i)"].to_i)
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def players_for_select
    User.all.collect{|b|[b.nickname || b.name, b.id]}
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-success">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Goats Golf League", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav float-xs-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'Leaderboard', leaderboard_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'This Year', this_year_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Last Year', last_year_path, class: 'nav-link' %></li>
<li class="nav-item"> <%= link_to "All Scores", scores_path, class: 'nav-link'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Golf" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Golf" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/leaderboard/last_year.html.erb
<% content_for :title do %>Last Years Leaderboard<% end %>
<h3>Last Year</h3>
<table class="table table-striped">
  <thead class="thead-default">
    <tr>
      <td><%= "Player" %></td>
      <td><%= "Best Score" %></td>
      <td><%= "2nd best Score" %></td>
      <td><%= "3rd best Score" %></td>
      <td><%= "Total points" %></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr scope="row">
        <td><%= image_tag user.avatar.url(:thumb), class: "avatar-thumb-small" %> <%= user.nickname %></td>
        <td><%= user.last_years_best_score %></td>
        <td><%= user.last_years_second_score %></td>
        <td><%= user.last_years_third_score %></td>
        <td><%= user.last_years_total_score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leaderboard/leaderboard.html.erb
<% content_for :title do %>Leaderboard<% end %>
<h3>Leaderboard</h3>
<table class="table table-striped">
  <thead class="thead-default">
    <tr>
      <td></td>
      <td><%= "Player" %></td>
      <td><%= "Rounds" %></td>
      <td><%= "Points" %></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr scope="row">
        <td><%= image_tag user.avatar.url(:thumb), class: "avatar-thumb-small" %> <%= user.nickname %></td>
        <td><%= user.total_rounds_this_year %></td>
        <td><%= image_tag user.avatar.url(:thumb), class: "avatar-thumb-small" %></td>
        <td><strong><%= user.nickname %></strong></td>
        <td><%= user.total_rounds %></td>
        <td><%= user.total_score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leaderboard/this_year.html.erb
<% content_for :title do %>This Years Leaderboard<% end %>
<h3>This Year</h3>
<table class="table table-striped">
  <thead class="thead-default">
    <tr>
      <td><%= "Player" %></td>
      <td><%= "Best Score" %></td>
      <td><%= "2nd best Score" %></td>
      <td><%= "3rd best Score" %></td>
      <td><%= "Total points" %></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr scope="row">
        <td><%= image_tag user.avatar.url(:thumb), class: "avatar-thumb-small" %> <%= user.nickname %></td>
        <td><%= user.best_score %></td>
        <td><%= user.second_score %></td>
        <td><%= user.third_score %></td>
        <td><%= user.total_score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This website will display details of the golf scores of the goats.
</p>

app/views/scores/_score.html.erb
<td><%= link_to score.user.nickname, user_path(score.user.id) %></td>
<td>
  <%= score.course %>
  <% if score.open_round %>
    <span class="float-sm-right text-danger">OPEN</span>
  <% end %>
</td>
<td><%= score.date.strftime("%d-%m-%Y") %></td>
<td class="hidden-sm-down"><%= score.handicap %></td>
<td><%= score.stableford %></td>
<td class="hidden-sm-down"><%= score.strokes %></td>

app/views/scores/index.html.erb
<div class="container">
  <div>
    <a href="/scores/new" class="btn btn-primary float-sm-right">Add a Score</a> 
    <h3>Scores</h3>
  </div>
  <table class="table table-striped">
    <thead class="thead-default">
      <tr>
        <td><%= "Player" %></td>
        <td><%= "Course" %></td>
        <td><%= "Date" %></td>
        <td class="hidden-sm-down"><%= "Handicap" %></td>
        <td><%= "Stableford" %></td>
        <td class="hidden-sm-down"><%= "Strokes" %></td>
      </tr>
    </thead>
    <tbody>
      <% if @scores.any? %>
      <% @scores.each do |score| %>
        <tr scope="row">
          <%= render score %>
        </tr>
      <% end %>
    <% else %>
      <p>No scores yet</P>
      <% end %>
    </tbody>
  </table>
</div>

app/views/scores/new.html.erb
<%= form_for @score do |f| %>
  <div class="form-group">
    <%= f.label :date %>
    <%= date_select :date, :date, selected: Date.today %>
  </div>
  <div class="form-group">
    <%= f.label "Player" %>
    <%= f.select :user_id, players_for_select, {}, prompt: "Select", id: "player-select", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :course %>
    <%= f.text_field :course, value: "Reigate Hill Golf Club", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :open_round %>
    <%= f.check_box :open_round, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :handicap %>
    <%= f.number_field :handicap, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :strokes %>
    <%= f.number_field :strokes, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :stableford %>
    <%= f.number_field :stableford, class: "form-control" %>
  </div>
  <%= f.submit 'Add score', :class => 'btn btn-primary' %>
<% end %>

app/views/users/_user.html.erb
<td><%= image_tag user.avatar.url(:thumb), class: "avatar-thumb" %></td>
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <% if f.object.class.require_password_on_accepting %>
  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>
  <% end %>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<table class="table table-striped">
  <thead class="thead-default">
    <tr>
      <td><%= "Player" %></td>
      <td><%= "Course" %></td>
      <td><%= "Date" %></td>
      <td class="hidden-sm-down"><%= "Handicap" %></td>
      <td><%= "Stableford" %></td>
      <td class="hidden-sm-down"><%= "Strokes" %></td>
    </tr>
  </thead>
  <tbody>
    <% if @user.scores.any? %>
      <% @user.scores.ordered.each do |score| %>
        <tr scope="row">
          <%= render score %>
        </tr>
      <% end %>
    <% else %>
      <p>No scores yet</P>
    <% end %>
  </tbody>
</table>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>